# Generated by Django 5.0.1 on 2024-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='body',
        ),
        migrations.AddField(
            model_name='intro',
            name='body_1',
            field=models.CharField(default='Add intro here', max_length=100000),
        ),
        migrations.AddField(
            model_name='intro',
            name='body_2',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='intro',
            name='body_3',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='intro',
            name='body_4',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='publication',
            name='bibtex',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
