# Generated by Django 5.0.1 on 2024-01-07 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_intro_body_intro_body_1_intro_body_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 22, 57, 417533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 22, 57, 417533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 22, 57, 417533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='thingsimplanning',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 22, 57, 417533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='workex',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 22, 57, 417533, tzinfo=datetime.timezone.utc)),
        ),
    ]
