# Generated by Django 5.0.1 on 2024-01-07 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_intro_created_at_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.CharField(default='Technologies used: ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='intro',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 41, 30, 35864, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 41, 30, 41006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 41, 30, 36703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thingsimplanning',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 41, 30, 37310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workex',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 8, 41, 30, 37988, tzinfo=datetime.timezone.utc)),
        ),
    ]
