# Generated by Django 5.0.1 on 2024-01-07 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_workex_duration_alter_intro_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workex',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 187399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='intro',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 185436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 190432, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 186129, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thingsimplanning',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 186740, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workex',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 2, 1, 187452, tzinfo=datetime.timezone.utc)),
        ),
    ]
