# Generated by Django 5.0.1 on 2024-01-07 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_workex_end_date_alter_intro_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='main_author',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='publication',
            name='other_authors',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='intro',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 936351, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 941521, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 937135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thingsimplanning',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 937764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workex',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 938467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workex',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 16, 49, 37, 938413, tzinfo=datetime.timezone.utc)),
        ),
    ]
